" Vim configuration

set nocompatible

" Pathogen
call pathogen#infect()

syntax enable
filetype plugin indent on

set showcmd
set showmode

set backspace=indent,eol,start

set hidden

set wildmenu
set wildmode=list:longest

set ignorecase
set smartcase

set number
set ruler

set incsearch
set hlsearch

set wrap
set scrolloff=3

set title

set nobackup
set nowritebackup
set directory=$HOME/.vim/tmp//,.

set tabstop=2
set shiftwidth=2
set softtabstop=2

color Tomorrow

