" Vim configuration

set nocompatible
filetype off

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'nanotech/jellybeans.vim'
Bundle 'scrooloose/nerdtree'

filetype plugin indent on
syntax enable

set showcmd
set showmode

set backspace=indent,eol,start

set hidden

set wildmenu
set wildmode=list:longest

set ignorecase
set smartcase

set number
set ruler

set incsearch
set hlsearch

set wrap
set scrolloff=3

set title

set noswapfile
set nobackup
set nowritebackup
set directory=$HOME/.vim/tmp//,.

" Use spaces instead of tabs
set expandtab 
set shiftwidth=2
set softtabstop=2

" set background=dark
color Tomorrow-Night

" transparent background
highlight Normal ctermbg=NONE

