gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - "#757581"
    selectedLineBgColor:
      - "#2a2a2d"
    selectedRangeBgColor:
      - "#2a2a2d"
  authorColors:
      "*": "blue"
