[theme]
name = "gruvbox-dark"

[theme.overrides]
idle_bg = "#1d1f21"
idle_fg = "#c5c8c6"
info_bg = "#5f819d"
info_fg = "#c5c8c6"
good_bg = "#8c9440"
good_fg = "#c5c8c6"
warning_bg = "#de935f"
warning_fg = "#ffffff"
critical_bg = "#a54242"
critical_fg = "#ffffff"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

