# misc
alias cls='clear'

# apt-get aliases
alias install='sudo apt-get install'
alias addrepo='sudo apt-add-repository'
alias remove='sudo apt-get remove'
alias autoremove='sudo apt-get autoremove'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias distupgrade='sudo apt-get dist-upgrade'

# git alises
alias gitc='git clone'
alias gitp='git push'
alias gits='git status'
alias gitaa='git add -A'

